const WORKOUT_DATA = [
  {
    weekday: 'M',
    date: '21',
    full_weekday: 'Monday',
    duration: '20min',
    month: 'SEP',
    title: 'Warm Up',
    excersises_set: [
      {
        title: 'Warm up',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Internal run',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Cool down',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
    ],
  },
  {
    weekday: 'T',
    date: '22',
    duration: '22min',
    full_weekday: 'Tuedday',
    month: 'SEP',
    title: 'Warm Up',
    excersises_set: [
      {
        title: 'Warm up',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Internal run',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Cool down',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
    ],
  },
  {
    weekday: 'W',
    date: '23',
    duration: '25min',
    full_weekday: 'Wednesday',
    month: 'SEP',
    title: 'Warm Up',
    excersises_set: [
      {
        title: 'Warm up',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Internal run',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Cool down',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
    ],
  },
  {
    weekday: 'T',
    date: '24',
    duration: '23min',
    full_weekday: 'Thursday',
    month: 'SEP',
    title: 'Warm Up',
    excersises_set: [
      {
        title: 'Warm up',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Internal run',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Cool down',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
    ],
  },
  {
    weekday: 'F',
    date: '25',
    duration: '21min',
    full_weekday: 'Friday',
    month: 'SEP',
    title: 'Warm Up',
    exercises: [
      { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
      { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
      { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
      { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
      { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
      { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
    ],
  },
  {
    weekday: 'S',
    date: '26',
    duration: '19min',
    full_weekday: 'Saturday',
    month: 'SEP',
    title: 'Warm Up',
    excersises_set: [
      {
        title: 'Warm up',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Internal run',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Cool down',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
    ],
  },
  {
    weekday: 'S',
    date: '27',
    duration: '28min',
    full_weekday: 'Sunday',
    month: 'SEP',
    title: 'Warm Up',
    excersises_set: [
      {
        title: 'Warm up',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Internal run',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
      {
        title: 'Cool down',
        exercises: [
          { id: 1, title: 'Arm Reach', time: '20s', sets: '2' },
          { id: 2, title: 'Side Reach', time: '20s', sets: '2' },
          { id: 3, title: 'Hip Rotations', time: '20s', sets: '2' },
          { id: 4, title: 'Knees Lift', time: '20s', sets: '2' },
          { id: 5, title: 'Squat With Reach', time: '20s', sets: '2' },
          { id: 6, title: 'Jumping Jack', time: '20s', sets: '2' },
        ],
      },
    ],
  },
];

export default WORKOUT_DATA;
